### ISSUE TITLE
Avoid placing shader files in `Resources` directories.

### ISSUE THREAD

**Issue by Santarh** [vrm-c/UniVRM#1341]
依存シェーダファイルを `Resources` ディレクトリに置くことをやめたい。

ShaderVariantCollection に揃える。

**Comment by andreiagmu** [comment]
I'm also interested in this update, so that my builds won't compile shader variants that I don't need (I don't use MToon on my project), and to also make my build size a little smaller.

In my tests, I've used a workaround: 
I copied the UniVRM-related packages to my <Project root>\Packages folder, then I renamed all "Resources" folders inside to "Resource". Then, it seems the VRM importer still works normally.

This workaround solves the extra shader variants/build size issue.
But putting the UniVRM packages in that custom Packages folder makes it much less intuitive to update the packages.

**Comment by Santarh** [comment]
ShaderVariantCollection で実現しようと思うと URP/Lit や Standard シェーダのバリアントを大量に登録せねばならず、登録した結果 Editor がクラッシュしたので断念。

ユーザは Always Included Shaders に登録するか、Addressable Assets の仕組みを使って管理する必要がある。
