### ISSUE TITLE
[0.x][1.0] images mimeType is not right

### ISSUE THREAD

**Issue by infosia** [vrm-c/UniVRM#1390]
## Environments

 - UniVRM version: `VRM-0.89.0_9470.unitypackage`
 - Unity version: `Unity-2019.4.29f1`
 - OS: `Windows 10`

## Describe the bug

According to the [glTF spec](https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#_image_mimetype), you don't need to escape "/" with "\\" string like `image\/png`. Just put `image/jpeg` and `image/png` would be just fine. See also: [specification/2.0/schema/image.schema.json](https://github.com/KhronosGroup/glTF/blob/main/specification/2.0/schema/image.schema.json#L19)

* Not right

```json
   "images":[
      {
         "name":"OccupyGuy_diffuse",
         "bufferView":28,
         "mimeType":"image\/jpeg"
      },
      {
         "name":"OccupyGuy_normal",
         "bufferView":29,
         "mimeType":"image\/png"
      },
      {
         "name":"OccupyGuy_FaceAnimMap",
         "bufferView":30,
         "mimeType":"image\/png"
      }
   ],
```

* Right

```json
   "images":[
      {
         "name":"OccupyGuy_diffuse",
         "bufferView":28,
         "mimeType":"image/jpeg"
      },
      {
         "name":"OccupyGuy_normal",
         "bufferView":29,
         "mimeType":"image/png"
      },
      {
         "name":"OccupyGuy_FaceAnimMap",
         "bufferView":30,
         "mimeType":"image/png"
      }
   ],
```

* Reproduction procedure

1. Import [kaya.fbx](https://github.com/infosia/themachinery-issues/blob/master/0011/kaya.fbx)
2. Place the fbx into the scene
3. `VRM1` -> `Export VRM 1.0`

* File that causes an error (those that can be pasted here)

https://github.com/infosia/themachinery-issues/blob/master/0011/kaya.fbx

**Comment by infosia** [comment]
This reminds me that the escape strings in URLs such as `licenseUrl` may not be needed too, I guess.

```JSON
"licenseUrl":"https:\/\/vrm.dev\/licenses\/1.0\/",
```

**Comment by Santarh** [comment]
Machine translated English follows Japanese.

報告ありがとうございます。
さてこちらの Issue ですが、結論から言うと現状で問題はないと考えています。
理由としては以下になります。

- glTF の仕様として、 mimeType の定義は、JSON の文字列として `image/png` `image/jpeg` であること
  - https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#_image_mimetype 
- JSON の仕様として、JSON の `"\/"` は合法であり、文字列 `/` として解釈できること
  - `/` はエスケープしてもいいし、エスケープしなくてもいい、という曖昧な立場にあることが読み取れます。
  - https://www.rfc-editor.org/info/rfc8259
  - https://www.json.org/json-en.html
- mimeType として `"image\/png"` を指定した glb ファイルが公式の glTF Validator で valid であること 
  - https://github.khronos.org/glTF-Validator/

おそらくこれは JSON と Web の歴史からくる `/` エスケープの問題だと考えています。
たしかに主観的には気持ち悪い問題だと感じますが、JSON として合法な以上は、UniVRM がどちらを出力しようとも対応せざるを得ないと考えます。

--------

Thank you for your report.
In conclusion, I don't think there is any problem at present.
The reason is as follows.

- As a glTF specification, the definition of mimeType is `image/png`` image/jpeg` as a JSON string.
  - https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#_image_mimetype 
- By JSON specification, JSON `"\/"` is legal and can be interpreted as a JSON string `/` .
  - You can read the ambiguity from the specification that `/` may or may not be escaped.
  - https://www.rfc-editor.org/info/rfc8259
  - https://www.json.org/json-en.html
- The glb file with `"image\/png"` as mimeType is valid with the official glTF Validator.
  - https://github.khronos.org/glTF-Validator/

Perhaps this is a `/` escape issue from the history of JSON and the Web.
It's certainly an unpleasant problem subjectively, but as long as it's legal as JSON, I think UniVRM has no choice but to deal with either output.

**Comment by infosia** [comment]
Thanks for the reply, 

I understand that the glTF importer should be taking care of escape strings based on the JSON specification, but it does not necessarily mean exporters should output these unwanted strings.

I think that the point is not about the validity of JSON nor glTF as a strict spec but it's about how it's actually handled in glTF normally. I can not see any glTF files from Khronos that interpret "/" as "\" neither in mime types nor URLs. (Did quick look at [glTF-Sample-Models](https://github.com/KhronosGroup/glTF-Sample-Models) and  [glTF-Validator](https://github.com/KhronosGroup/glTF-Validator)) 

Also that this comes to my mind: the simple question would be that "_Why would you output the escape strings that is not necessary actually?_" It does append unwanted bytes and makes it harder to read, and forces importer to escape unwanted escape strings.

**Comment by Santarh** [comment]
Low priority
