### ISSUE TITLE
Re-add option to export with vertex colors

### ISSUE THREAD

**Issue by Loder333** [vrm-c/UniVRM#1413]
**Environment**

OS: Windows 10 Build 19043.1348
Unity Version: 2019.4.16f1
UniVRM Version: 0.90.0

**Details**

In prior versions (Starting around 0.56.x, not sure when it was removed), the option to export with or without vertex colors was available. In 0.90.0, the option appears to be gone. UniVRM now automatically exports without vertex colors. It seems intentional but maybe it's a bug? The option to export with vertex colors intact is important, because when using a VRM where other shaders are supported (e.g. VSeeFace), having the vertex colors allows the use of various features in certain shaders. In my case, I use vertex colors as a mask in poiyomi to determine where outlines should be drawn. In order to do so I am forced to use an older version of UniVRM since the current one seems to remove them automatically.

**Comment by ousttrue** [comment]
Thank you for reporting.
The former uniVRM behavior was to keep vertex color, but the recent behavior is removal.

Because, 
* 'MToon' and 'Standard' do not support vertex color.
* GLTF cannot have a data representation that stores vertex color but does not draw.

I'll add the option to export vertex color for special purposes.

**Comment by ousttrue** [comment]
`v0.91.0`
Add `Keep vertex color` option.

![keep_vertex_color](https://user-images.githubusercontent.com/68057/145389569-9dfb2253-ff37-4766-8846-0d3b64cb51c6.jpg)
