### ISSUE TITLE
特定のVRM1 BetaモデルインポートでAssertion failed on expression: 'ValidTRS()'が発生

### ISSUE THREAD

**Issue by saturday06** [vrm-c/UniVRM#1614]
## 環境情報

 - UniVRM version: `0.97.0`
 - Unity version: `Unity-2021.3.0f1`
 - OS: `Windows 11 Pro 21H2 22000.613` `macOS Monterey 12.3.1`

## バグについて

* バグの内容

[添付したVRM1 Betaの再現ファイル](https://github.com/vrm-c/UniVRM/files/8500721/OrientationTest.vrm.zip) を `Assets` フォルダ以下に配置すると `UniGLTF.UnityExtensions:ExtractRotation()` 内のUnity API呼び出しでAssertion Failed on expression: "ValidTRS()"が発生します。

- 再現ファイルをglTF Validatorにかけたところエラーは発生していませんでした。
- 拡張子を.glbに変更して `Assets` フォルダに配置すると正常にインポートが完了しました。

* ConsoleLog

```
Assertion failed on expression: 'ValidTRS()'
UnityEngine.Matrix4x4:get_rotation ()
UniGLTF.UnityExtensions:ExtractRotation (UnityEngine.Matrix4x4) (at Library/PackageCache/com.vrmc.gltf@ac3083c270/Runtime/Extensions/UnityExtensions.cs:218)
UniGLTF.UnityExtensions:Decompose (UnityEngine.Matrix4x4) (at Library/PackageCache/com.vrmc.gltf@ac3083c270/Runtime/Extensions/UnityExtensions.cs:102)
VrmLib.Node:SetLocalMatrix (UnityEngine.Matrix4x4,bool) (at Library/PackageCache/com.vrmc.vrm@ac3083c270/vrmlib/Runtime/Node.cs:84)
UniVRM10.Vrm10ImportData:CreateNode (int) (at Library/PackageCache/com.vrmc.vrm@ac3083c270/Runtime/IO/Vrm10ImportData.cs:373)
UniVRM10.ModelReader:Load (UniVRM10.Vrm10ImportData,string,VrmLib.Coordinates) (at Library/PackageCache/com.vrmc.vrm@ac3083c270/Runtime/IO/Model/ModelReader.cs:32)
UniVRM10.ModelReader:Read (UniGLTF.GltfData,System.Nullable`1<VrmLib.Coordinates>) (at Library/PackageCache/com.vrmc.vrm@ac3083c270/Runtime/IO/Model/ModelReader.cs:81)
UniVRM10.Vrm10Importer:<LoadAsync>b__8_0 () (at Library/PackageCache/com.vrmc.vrm@ac3083c270/Runtime/IO/Vrm10Importer.cs:94)
VRMShaders.ImmediateCaller:Run (System.Action) (at Library/PackageCache/com.vrmc.vrmshaders@ac3083c270/GLTF/IO/Runtime/AwaitCaller/ImmediateCaller.cs:18)
UniVRM10.Vrm10Importer/<LoadAsync>d__8:MoveNext () (at Library/PackageCache/com.vrmc.vrm@ac3083c270/Runtime/IO/Vrm10Importer.cs:91)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<UniGLTF.RuntimeGltfInstance>:Start<UniVRM10.Vrm10Importer/<LoadAsync>d__8> (UniVRM10.Vrm10Importer/<LoadAsync>d__8&)
UniVRM10.Vrm10Importer:LoadAsync (VRMShaders.IAwaitCaller,System.Func`2<string, System.IDisposable>)
UniGLTF.ImporterContextExtensions:Load (UniGLTF.ImporterContext) (at Library/PackageCache/com.vrmc.gltf@ac3083c270/Runtime/UniGLTF/IO/ImporterContextExtensions.cs:15)
UniVRM10.VrmScriptedImporterImpl:Process (UniVRM10.Vrm10Data,UnityEditor.AssetImporters.ScriptedImporter,UnityEditor.AssetImporters.AssetImportContext,UniGLTF.RenderPipelineTypes,bool) (at Library/PackageCache/com.vrmc.vrm@ac3083c270/Editor/ScriptedImporter/VrmScriptedImporterImpl.cs:53)
UniVRM10.VrmScriptedImporterImpl:Import (UnityEditor.AssetImporters.ScriptedImporter,UnityEditor.AssetImporters.AssetImportContext,bool,UniGLTF.RenderPipelineTypes,bool) (at Library/PackageCache/com.vrmc.vrm@ac3083c270/Editor/ScriptedImporter/VrmScriptedImporterImpl.cs:89)
UniVRM10.VrmScriptedImporter:OnImportAsset (UnityEditor.AssetImporters.AssetImportContext) (at Library/PackageCache/com.vrmc.vrm@ac3083c270/Editor/ScriptedImporter/VrmScriptedImporter.cs:25)
UnityEditor.AssetImporters.ScriptedImporter:GenerateAssetData (UnityEditor.AssetImporters.AssetImportContext)
```

* スクリーンショット

再現ファイルの拡張子を `.glb` に変更し、 `Assets` フォルダにコピーするとエラー無くPrefabが作成されます。そのPrefabをシーンに追加した状態のスクリーンショットです。正常に動作した場合もこのスクリーンショットのようになることを期待します。

<img src="https://user-images.githubusercontent.com/532872/163693172-77b8bcff-f6d2-4c38-ba19-04091dc51231.png" width="300">

glTF 2.0サンプルモデルのOrientationTestモデルに手足をつけたものになります。

* 再現方法
(バグ内容に記載)

* エラーの発生するファイル(ここに貼り付けても差し支えの無いもの)
[OrientationTest.vrm.zip](https://github.com/vrm-c/UniVRM/files/8500721/OrientationTest.vrm.zip)

**Comment by ousttrue** [comment]
報告ありがとうございます。
`new Matrix4x4()` の引数が transpose していたようです。
修正します。

**Comment by ousttrue** [comment]
`v0.99.0` で修正されます。
Matrix4x4 transpose(bug), uint8 型の indices, NORMAL が無いに対応。

**Comment by 956zs** [comment]
## Environments

- **UniVRM version**: `VRM-0.129.0_027e`
- **Unity version**: `Unity-2022.3.22f1`
- **OS**: `Windows 11`

## Describe the bug

- **A clear and concise description of what the bug is**:  
  When exporting an avatar to VRM1.0 format using UniVRM, the export process fails after filling in the required fields (`Name` and `Authors`) in the export dialog. The Unity console displays an error indicating an assertion failure on `ValidTRS()`, suggesting an issue with the model's transform matrix during matrix decomposition or coordinate conversion.

- **ConsoleLog**:  
  ```
  Assertion failed on expression: 'ValidTRS()'
  UnityEngine.Matrix4x4:get_rotation ()
  UniGLTF.UnityExtensions:ExtractRotation (UnityEngine.Matrix4x4) (at Assets/UniGLTF/Runtime/Extensions/UnityExtensions.cs:218)
  UniGLTF.UnityExtensions:Decompose (UnityEngine.Matrix4x4) (at Assets/UniGLTF/Runtime/Extensions/UnityExtensions.cs:102)
  VrmLib.Node:SetLocalMatrix (UnityEngine.Matrix4x4,bool) (at Assets/VRM10/vrmlib/Runtime/Node.cs:84)
  VrmLib.Node:SetMatrix (UnityEngine.Matrix4x4,bool) (at Assets/VRM10/vrmlib/Runtime/Node.cs:117)
  VrmLib.Model:ReverseAxisAndFlipTriangle (VrmLib.Model/Reverser,bool) (at Assets/VRM10/vrmlib/Runtime/Model.cs:497)
  VrmLib.Model:ConvertCoordinate (VrmLib.Coordinates,bool) (at Assets/VRM10/vrmlib/Runtime/Model.cs:389)
  UniVRM10.VRM10ExportDialog:ExportPath (string) (at Assets/VRM10/Editor/Vrm10ExportDialog.cs:315)
  UniGLTF.ExportDialogBase:EndGUI () (at Assets/UniGLTF/Editor/UniGLTF/ExportDialog/ExportDialogBase.cs:161)
  UniGLTF.ExportDialogBase:OnGUI () (at Assets/UniGLTF/Editor/UniGLTF/ExportDialog/ExportDialogBase.cs:82)
  UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
  ```

- **ScreenShot**:  
 ![Image](https://github.com/user-attachments/assets/23bc479e-7b1c-436f-a892-c44926f327bd)


- **Reproduction procedure**:  
  1. Open a Unity project (Unity 2022.3.22f1) with UniVRM (VRM-0.129.0_027e) already imported.
  2. Ensure an avatar model is set up in the scene (compatible with VRM, e.g., with a Humanoid Rig).
  3. From the Unity menu bar, navigate to `VRM1.0` and select the export option to open the VRM1.0 export dialog.
  4. Fill in all required fields in the export dialog, including `Name` and `Authors`.
  5. Click the export button and select a valid file path for the VRM file.
  6. The export process fails, and the above error appears in the Unity console.

- **File that causes an error**:  
i am not sure
