### ISSUE TITLE
UV Map Limitation Issue

### ISSUE THREAD

**Issue by KanaFuyuko** [vrm-c/UniVRM#1701]
## Environments (please complete the following information):

 - UniVRM version: `0.95.1`
 - Unity version: `Unity-2019.4.31`
 - OS: `Windows 10`

## Describe the bug

When a model gets exported with more than two UV maps from Blender to Unity under the FBX format to be converted to the VRM format, the extra UVs inside of the model (For example, a model with 10 UV maps) would end up disappearing with both UniGLTF and UniVRM export and only two UV maps will be fine. (To put it simply, UniVRM seems to only limit up to two UV maps when it should allow more UV maps like up to 10 count)

Procedure:
-In Blender, have a model that includes at least about 5-10 UV maps
-Export that model into the FBX format
-Import the FBX file to Unity 2019.4.31
-Set up FBX and export to VRM format
-Import VRM file back to Unity
-When VRM file gets imported back to Unity, you will notice some UV map data missing and only two of them will stay as if the limitation for UniVRM is two UV maps only

**Comment by ousttrue** [comment]
Thank you for reporting.
Unity's Standard and glTF materials are not compatible with multiple UV behaviors.
It is possible to implement import / export of multiple UVs. 
However, material import / export does not use the correct UVs.

**Comment by Teiksomaksou** [comment]
UniVRM 0.110.0
Unity 2019.4.31f

Multiple UV maps are actually preserved after normalization and export of VRM avatar. Placing any advanced shader on re-imported VRM avatar allows access and usage of secondary UV maps inside Unity. 
The problem is the lack of support for selecting this UV map inside MToon shader. This could allow us to use detail and emission maps, making toggles by UV swap with alpha clip transparency (but only if it was able to access this MToon properties by vrm blendshape material clip).
