### ISSUE TITLE
NullReferenceException in BlendShapeProxyValidator

### ISSUE THREAD

**Issue by Wolfstrike18** [vrm-c/UniVRM#1709]
## Environments (please complete the following information):

 - UniVRM version: `0.100.1`
 - Unity version: `Unity-2019.4.31f1`
 - OS: `Windows 11`

## Describe the bug

* A clear and concise description of what the bug is.
* ConsoleLog
![image_2022-06-23_174002591](https://user-images.githubusercontent.com/108101066/175426657-9c936947-c5fe-49b0-87d2-c36a8fba670a.png)

* ScreenShot
* Any time I try to export the model to use It ends up flashing the export screen any time I move the mouse, and my console is flooded with these errors, If i try to export anyways the screen just goes away and doesnt export
* File that causes an error (those that can be pasted here)

**Comment by ousttrue** [comment]
Thank you for reporting.
This error occurs when the blendShape list of blendShapeavatar contains null.

![null_clip](https://user-images.githubusercontent.com/68057/178653447-2c1f75ac-75cd-4fbc-9c9a-475f3a32a80d.jpg)

In the next version, fix it so that it doesn't cause an error even if it contains null.
