### ISSUE TITLE
WebGL UniTask

### ISSUE THREAD

**Issue by michaellu88** [vrm-c/UniVRM#1745]
Will u add UniTask Support for WebGL? since WebGL doesn't support multithreading, loading vrm at runtime will freeze the screen for a couple of seconds. tq

**Comment by michaellu88** [comment]
Convert every function to unitask with async await as much as possible. And testing unitask. Delay for few seconds to find out where it freeze, found out that UniJson parsing and deserialise cause most of the freeze. It is possible to remove json file or using more efficient json parsing for runtime import? I have open another issue on this json parsing.

**Comment by michaellu88** [comment]
UPDATE 
texture.LoadImage(textureInfo.ImageData);

texture LoadImage freeze 1/2 a seconds as well. trying to replace with LoadRawTextureData, althought it doesn't freeze but no colour loaded.

**Comment by Santarh** [comment]
Thanks for your reporting.
We do not support fully non-blocking loads in single-threaded environments such as WebGL.

If we supported UniTask officially, you won't get the results you want.
Because WebGL doesn't support multithreading and the method of parsing JSON is implemented by `Task.Run` at current version.
Also blocking the main thread while loading texture is depend on internal UnityEngine's implementation.
`new Texture2D()` always causes blocking the main thread.

**Comment by michaellu88** [comment]
for texture.loadimage maybe we can solve by using native renderingPlugin  as mention in https://stackoverflow.com/questions/54749373/hololens-unity-loadimage-freezes-main-thread

or webglmovietexture as mention in https://stackoverflow.com/questions/56123201/unity-plugin-texture-is-immutable

i will try to implement it and reporting back.

**Comment by Santarh** [comment]
You can implement `ITextureDeserializer` with native plugin for your target environments and pass to importer constructor. 😉

**Comment by breadnone** [comment]
UniTask works in WebGL as long as you're not using Task.Run or switching to the threadPool in general.
