### ISSUE TITLE
Blendshapes don't look the same way

### ISSUE THREAD

**Issue by AspieCow** [vrm-c/UniVRM#1766]
- UniVRM version: `0.98.0`
 - Unity version: `Unity-2021.3.3f1`
 - OS: `Windows 10`

Hi. I use Blender for modeling.  It has already happened before to my previous models so it's not a new issue. 
I export fbx straight to unity without using CATS, and then convert it to vrm.

Seems like the vertexes slightly change their position, but it's enough to ruin my workflow.

Do you have any idea what could cause this issue? 

![1](https://user-images.githubusercontent.com/105969493/183424991-d2db5cb4-1af0-4612-9cc1-99fb0a481a41.png)

**Comment by ousttrue** [comment]
Could it be related to https://github.com/vrm-c/UniVRM/issues/597 ?

The lines are presumed to be MToon's boundaries.
MToon borders are affected by the normal direction.
When the normal direction is automatically calculated, in the part where the mesh is not connected (around the mouth), the normals of adjacent faces are different, and the boundary line of MToon is visible.
merge vertices in blender might stop it from happening.
Otherwise, care must be taken to avoid auto-computing normals at each step.
