### ISSUE TITLE
Automatic conversion from legacy VRM formats to VRM 1.0 format

### ISSUE THREAD

**Issue by nick008a** [vrm-c/UniVRM#1794]
Is it possible to convert the old vrm format to vrm-1.0 format automatically?

**Comment by ousttrue** [comment]
Yes, it is possible to do automatic conversion with runtime imports.
No, automatically export vrm 0.x binaries as vrm-1.0 binaries.

details:

We have implemented a function to import all Vrm-0.x as Vrm-1.0, so that there is no need to automatically convert vrm-0.x to vrm-1.0.
see
<https://vrm-c.github.io/UniVRM/ja/vrm1/vrm1_load.html#migration-vrm-0-to-vrm-1>

On the other hand, automatic conversion (exporting vrm-1.0 binary) is not implemented.
This is because we want the vrm owner to confirm the license conversion.
