### ISSUE TITLE
[URP] MToon10 Outline 

### ISSUE THREAD

**Issue by HongDeveloper** [vrm-c/UniVRM#2265]
<img width="426" alt="image" src="https://github.com/vrm-c/UniVRM/assets/122740179/e6b63bf7-4ea2-421a-8b2c-dc5c12067a8e">
<img width="595" alt="Screenshot 2024-03-18 at 18 46 03" src="https://github.com/vrm-c/UniVRM/assets/122740179/449841c5-dbfa-464b-9b2a-f24779700606">
<img width="438" alt="image" src="https://github.com/vrm-c/UniVRM/assets/122740179/9d921d5a-193a-4542-b0fa-c0a527fcc4fa">

 - UniVRM version: `v.0.12.0`
 - Unity version: `Unity-2021.3`
 - OS: `Mac, Window`

## Describe the bug
Hi. I have a issue 
Adjusting the outline value doesn't change.
It's not even visible
Package is recent release.

**Comment by sack-kazu** [comment]
Maybe adding "MToonOutlineRenderFeature" Render Feature will help!
![image](https://github.com/vrm-c/UniVRM/assets/52432227/f60602c1-c9d6-4e12-baa8-6933cf266c19)

**Comment by kaioduarte** [comment]
Adding the outline render feature doesn't make a difference to me 🤷🏻

**Comment by kaioduarte** [comment]
I managed to get the outline working on URP by adding this pass to the shader (`Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_urp.shader`)

```hlsl
// MToon Outline Pass
...

Pass
{
  Name "Outline"
  Cull Front
  Tags { "LightMode" = "SRPDefaultUnlit" }

  HLSLPROGRAM
  #pragma vertex vert
  #pragma fragment frag
  #pragma multi_compile_fog

  #define MTOON_URP

  #include "./vrmc_materials_mtoon_render_pipeline.hlsl"
  #include "./vrmc_materials_mtoon_input.hlsl"

  struct appdata
  {
    float4 vertex  : POSITION;
    float3 normal  : NORMAL;
    float2 uv      : TEXCOORD0;
  };

  struct v2f
  {
    float4 pos      : SV_POSITION;
    half2 uv        : TEXCOORD1;
  };

  v2f vert(appdata v)
  {
    v2f output;

    output.pos = MToon_TransformObjectToHClip(float4(v.vertex.xyz + v.normal * _OutlineWidth * 0.1, 1));
    output.uv = v.uv;

    return output;
  }

  float4 frag(v2f i) : SV_Target
  {
    half4 texColor = MTOON_SAMPLE_TEXTURE2D(_MainTex, i.uv);

    if (texColor.a <= _Cutoff) {
      discard;
    }

    return _OutlineColor;
  }

  ENDHLSL
}
```

**Comment by WilsonCWong** [comment]
Turn off 'Depth Priming Mode' in your renderer, Unity's toon shader has a similar issue with their outlines: https://docs.unity3d.com/Packages/com.unity.toonshader@0.9/manual/Known-issue.html#when-using-universal-render-pipeline

**Comment by kaioduarte** [comment]
That option was already disabled for me and it didn't help.

**Comment by Kwajik** [comment]
Thx 👍

**Comment by kirelisaurimas** [comment]
The error is still present in newest shader version. While editing shader makes it visible, it introduces some performance issues in my case. Also this warning might give more clues. as it is spammed in warning tab when I added outline feature;

The render pass VRM10.MToon10.MToonOutlineRenderPass does not have an implementation of the RecordRenderGraph method. Please implement this method, or consider turning on Compatibility Mode (RenderGraph disabled) in the menu Edit > Project Settings > Graphics > URP. Otherwise the render pass will have no effect. For more information, refer to https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@latest/index.html?subfolder=/manual/customizing-urp.html.
