### ISSUE TITLE
Unity2019.1対応

### ISSUE THREAD

**Issue by hiroj** [vrm-c/UniVRM#237]
* MToonの表示に不具合あり
* その他不具合を調査中

**Comment by SetoKaiba** [comment]
I use frame debugger and find that the keyword is lost. I reported a bug to Unity and didn't get any reply yet.

**Comment by hiroj** [comment]
Thanks for the report

**Comment by hiroj** [comment]
https://github.com/Santarh/MToon/issues/44

**Comment by SetoKaiba** [comment]
@hiroj After a deeper dig, I found out the problem is caused by the line below.
`UsePass "Standard/SHADOWCASTER"`
The problem is introduced by the new modification on Standard.shader. It uses shader_feature_local instead of shader_feature.
The shader_feature_local will just make the keywords for multi_compile and shader_feature not working anymore.
And also, the problem can't be reverted. Once you compiled the shader with shader_feature_local. Even you remove the lines.
The keyword will still not work.

The temp workaround is to delete the shader. And use the code below for a temp fix. I'll still wait for the replies from official and give more updates here.
```
			Pass {
				Name "ShadowCaster"
				Tags { "LightMode" = "ShadowCaster" }

				ZWrite On ZTest LEqual

				CGPROGRAM
				#pragma target 3.0

				// -------------------------------------


				#pragma shader_feature _ _ALPHATEST_ON _ALPHABLEND_ON _ALPHAPREMULTIPLY_ON
				#pragma shader_feature _METALLICGLOSSMAP
				#pragma shader_feature _SMOOTHNESS_TEXTURE_ALBEDO_CHANNEL_A
				#pragma shader_feature _PARALLAXMAP
				#pragma multi_compile_shadowcaster
				#pragma multi_compile_instancing
				// Uncomment the following line to enable dithering LOD crossfade. Note: there are more in the file to uncomment for other passes.
				//#pragma multi_compile _ LOD_FADE_CROSSFADE

				#pragma vertex vertShadowCaster
				#pragma fragment fragShadowCaster

				#include "UnityStandardShadow.cginc"

				ENDCG
			}
```

**Comment by SetoKaiba** [comment]
MToon merged the workaround. Maybe update the MToon for VRM as well?

**Comment by hiroj** [comment]
Yes, fetch updates and advance versions.

**Comment by hiroj** [comment]
Supported by version 0.52
