### ISSUE TITLE
GLB, Glass material problem

### ISSUE THREAD

**Issue by kknsy** [vrm-c/UniVRM#244]
unity editor is Normal ,but Publish exe or HoloLens is not Normal
![image](https://user-images.githubusercontent.com/26211860/57567381-e4491300-740a-11e9-9686-259cd30e306f.png)
![image](https://user-images.githubusercontent.com/26211860/57567383-ea3ef400-740a-11e9-8620-54a43435b8a3.png)

[bl_2.zip](https://github.com/vrm-c/UniVRM/files/3168808/bl_2.zip)
@yutopp

**Comment by kknsy** [comment]
This problem is very reproducible. I don't know if you have tested this problem on the other side. Can you provide a solution? Because you suddenly find this problem in your project integration project. @hiroj

**Comment by hiroj** [comment]
Unity extracts and uses only Shader patterns used in Project at build time.
Therefore, the cause of this phenomenon is that some features of StandardShader have been removed by optimization at build time.

Edit> Project Settings> Graphics> Shaders Always Included
Add StandardShader with the above settings.
This ensures that all StandardShader features are always available after build, regardless of the state of the project.
However, because all the features of StandardShader are compiled, the build time will be longer.

![image](https://user-images.githubusercontent.com/39366194/57914621-f1ae4380-78c9-11e9-8f32-33660d8f574e.png)

**Comment by kknsy** [comment]
thank you very much，It is indeed this problem。in order to avoid the build time will be longer，I take another way，A new glass material object is created in the scene，Ensure that the glass material is not optimized to remove, which can also solve this problem.  @hiroj
