### ISSUE TITLE
Using VRMBlendShapeProxy.AccumulateValue can result in blendshape values above 100

### ISSUE THREAD

**Issue by Deatrathias** [vrm-c/UniVRM#458]
When multiple Blendshape clips have the same blendshape, the values in each clip will be added together when using AccumulateValue. This can result in the blendshape getting a value above 100, which can look strange in many circumstances.

**Comment by PoChang007** [comment]
Hi,
If the vertex used by multiple BlendShape, setting blendshape Max value as 100 probably won't help improve the result. For example, setting the value of each Blendshape clip (Alicia model ) to 1 with the condition that each blendshape's max value is 100, the Alicia's face still looks strange.

**Comment by emilianavt** [comment]
Hi,
I am working on a face tracking application and some users reported issues due to this. The current behaviour caused trouble because the models that had both the Blink_L and Blink_R blend shape clips configured with EYE_Close at 100 to close both eyes. My program controlls the eyes individually and it lead to clipping, because the eyes were closed with a strength of 200. It also caused issues with mixing mouth related blend shape clips and the VRoid fang blendshape.
Changing the accumulation function from addition to Mathf.Max seems to fix these issues.

**Comment by PoChang007** [comment]
Just did some tests. It looks like BlendShape strength does not clamp to the range [0,100] in Unity 2019. I compared 2019.3 with 2018.4, not sure other versions. 
Changing to blendshape Max = 100 indeed fixes the case you mentioned.

**Comment by PoChang007** [comment]
Thanks for pointing out this issue
