### ISSUE TITLE
VRM T-POSE SCRAW THE MODEL

### ISSUE THREAD

**Issue by DemonRem** [vrm-c/UniVRM#908]
nothing to say & describ i belive the image say everything
this done after pressing "freeze t-pose" look at her foot.
![1](https://user-images.githubusercontent.com/29927382/115893490-e920f900-a460-11eb-8376-ed3ad8534105.png)

**Comment by PoChang007** [comment]
Hi,

We suspect this model's bone structure is like:

- root
 * shoes
 * hips - legs - foot

It should be fine If the structure looks like the following:

- root
 * hips - legs - foot - shoes

**Comment by KanaFuyuko** [comment]
TDA models tend to have issues if you use MMD4Mecanim. This is because TDA models have IK bones and the D and EX bones, use Cats Blender tools to automatically remove those bones and correct the structure or manually fix the model in PMX Editor. Also you can freeze transformations and have a custom T pose (Usually not recommended unless there is a tracking issue like thumb direction) when you export as FBX and select the option for Apply Transformations on the bottom right of the export screen.

**Comment by ousttrue** [comment]
If you have any problems with the latest version, please report it again.
